
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 11 15:59:59 GMT-03:00 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Class = 6;
  public static final int Divisao = 19;
  public static final int Op = 26;
  public static final int True = 33;
  public static final int FechaParentese = 21;
  public static final int If = 8;
  public static final int Void = 4;
  public static final int Static = 3;
  public static final int FechaChave = 25;
  public static final int ConstString = 32;
  public static final int PontoVirgula = 13;
  public static final int Else = 9;
  public static final int E = 38;
  public static final int ConstReal = 31;
  public static final int AbreChave = 24;
  public static final int OpUnario = 27;
  public static final int While = 10;
  public static final int AbreParentese = 20;
  public static final int Digito = 29;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int DeclaracaoVar = 37;
  public static final int error = 1;
  public static final int False = 34;
  public static final int Println = 12;
  public static final int Soma = 16;
  public static final int Print = 11;
  public static final int ERROR = 39;
  public static final int AbreCochete = 22;
  public static final int Virgula = 14;
  public static final int Multiplicacao = 18;
  public static final int Public = 2;
  public static final int FechaCochete = 23;
  public static final int New = 7;
  public static final int ConstInteira = 30;
  public static final int Retorno = 36;
  public static final int Main = 5;
  public static final int Igual = 15;
  public static final int Subtracao = 17;
  public static final int TipoPrimitivo = 28;
}

