/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;

/**
 *
 * @author Windows
 */
public class tela_analisador extends javax.swing.JFrame {
    
    static int linha_erro=1;
    static int coluna_erro=1;

    /**
     * Creates new form tela_analizador
     */
    public tela_analisador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_sintatico = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        analise_sintatica_txt = new javax.swing.JTextArea();
        btn_analise_sintatica = new javax.swing.JButton();
        btn_limpar_sintatico = new javax.swing.JButton();
        painel_lexico = new javax.swing.JPanel();
        btn_abrir_arquivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_entrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        analise_lexica_txt = new javax.swing.JTextArea();
        btn_analise_lexica = new javax.swing.JButton();
        btn_limpar_lexico = new javax.swing.JButton();
        btn_limpar_entrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_sintatico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analisador Sintático", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)));

        analise_sintatica_txt.setEditable(false);
        analise_sintatica_txt.setColumns(20);
        analise_sintatica_txt.setRows(5);
        jScrollPane6.setViewportView(analise_sintatica_txt);

        btn_analise_sintatica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_analise_sintatica.setText("Analisar Sintático");
        btn_analise_sintatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analise_sintaticaActionPerformed(evt);
            }
        });

        btn_limpar_sintatico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_limpar_sintatico.setText("Limpar");
        btn_limpar_sintatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_btn_limpar_sintaticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_sintaticoLayout = new javax.swing.GroupLayout(painel_sintatico);
        painel_sintatico.setLayout(painel_sintaticoLayout);
        painel_sintaticoLayout.setHorizontalGroup(
            painel_sintaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sintaticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_sintaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(painel_sintaticoLayout.createSequentialGroup()
                        .addComponent(btn_analise_sintatica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                        .addComponent(btn_limpar_sintatico))))
        );
        painel_sintaticoLayout.setVerticalGroup(
            painel_sintaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_sintaticoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painel_sintaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_analise_sintatica)
                    .addComponent(btn_limpar_sintatico))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_lexico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analisador Léxico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)));

        btn_abrir_arquivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_abrir_arquivo.setText("Abrir arquivo");
        btn_abrir_arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrir_arquivoActionPerformed(evt);
            }
        });

        txt_entrada.setColumns(20);
        txt_entrada.setRows(5);
        jScrollPane1.setViewportView(txt_entrada);

        analise_lexica_txt.setEditable(false);
        analise_lexica_txt.setColumns(20);
        analise_lexica_txt.setRows(5);
        jScrollPane2.setViewportView(analise_lexica_txt);

        btn_analise_lexica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_analise_lexica.setText("Analisar Léxico");
        btn_analise_lexica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analise_lexicaActionPerformed(evt);
            }
        });

        btn_limpar_lexico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_limpar_lexico.setText("Limpar");
        btn_limpar_lexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_lexicoActionPerformed(evt);
            }
        });

        btn_limpar_entrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_limpar_entrada.setText("Limpar");
        btn_limpar_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_entradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_lexicoLayout = new javax.swing.GroupLayout(painel_lexico);
        painel_lexico.setLayout(painel_lexicoLayout);
        painel_lexicoLayout.setHorizontalGroup(
            painel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_lexicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_abrir_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btn_limpar_entrada)
                .addGap(18, 18, 18)
                .addGroup(painel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel_lexicoLayout.createSequentialGroup()
                        .addComponent(btn_analise_lexica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_limpar_lexico))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(painel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_lexicoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );
        painel_lexicoLayout.setVerticalGroup(
            painel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_lexicoLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(painel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_analise_lexica)
                    .addComponent(btn_limpar_lexico)
                    .addComponent(btn_abrir_arquivo)
                    .addComponent(btn_limpar_entrada))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_lexicoLayout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_lexico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_sintatico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painel_lexico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painel_sintatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painel_sintatico.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_analise_sintaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analise_sintaticaActionPerformed
        // TODO add your handling code here:
        String ST = txt_entrada.getText();
        Sintax s = new Sintax(new codigo.LexerCup(new StringReader(ST)));
        
        try {
            s.parse();
            analise_sintatica_txt.setText("Análise realizada corretamente.");
            analise_sintatica_txt.setForeground(new Color(25, 111, 61));
        } catch (Exception ex) {
            Symbol sym = s.getS();
            analise_sintatica_txt.setText("Erro de sintaxe. Linha: "+(sym.right + 1)+ 
                                          " Coluna: "+(sym.left + 1)+ 
                                          ", Texto: \""+sym.value+"\"");
            analise_sintatica_txt.setForeground(Color.red);
        }
    }//GEN-LAST:event_btn_analise_sintaticaActionPerformed

    private void btn_btn_limpar_sintaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_btn_limpar_sintaticoActionPerformed
        // TODO add your handling code here:
        analise_sintatica_txt.setText(null);
    }//GEN-LAST:event_btn_btn_limpar_sintaticoActionPerformed

    private void btn_limpar_lexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_lexicoActionPerformed
        // TODO add your handling code here:
        analise_lexica_txt.setText(null);
    }//GEN-LAST:event_btn_limpar_lexicoActionPerformed

    private void btn_analise_lexicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analise_lexicaActionPerformed
        // TODO add your handling code here:
        File arquivo=new File("arquivo.txt");
        try {
            try (PrintWriter escrever = new PrintWriter(arquivo)) {
                escrever.print(txt_entrada.getText());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(tela_analisador.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Reader leitor=new BufferedReader(new FileReader("arquivo.txt"));
            Lexer lexer=new Lexer(leitor);
            String resultado="";
            while(true){
                Tokens tokens=lexer.yylex();
                if(tokens==null){
                    resultado+="FIM.";
                    analise_lexica_txt.setText(resultado);
                    linha_erro=1;
                    coluna_erro=1;
                    return;
                }
                switch(tokens){
                    case ERROR:
                    resultado+="Símbolo não identificado na linha "+linha_erro+" e coluna "+coluna_erro+".\n";
                    coluna_erro++;
                    break;
                    case Enter:
                    linha_erro++;
                    coluna_erro=1;
                    break;
                    case Tab:
                    coluna_erro=coluna_erro+3;
                    case E:
                    coluna_erro++;
                    break;
                    default:
                    resultado+=lexer.lexeme+" é um "+tokens+"\n";
                    String tamanho_token=lexer.lexeme;
                    int tamanho=tamanho_token.length();
                    for(int i=0; i<tamanho; i++) coluna_erro++;
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(tela_analisador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(tela_analisador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_analise_lexicaActionPerformed

    private void btn_abrir_arquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrir_arquivoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = new File(chooser.getSelectedFile().getAbsolutePath());

        try{
            String ST = new String(Files.readAllBytes(archivo.toPath()));
            txt_entrada.setText(ST);
        }catch (FileNotFoundException ex) {
            Logger.getLogger(tela_analisador.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException ex) {
            Logger.getLogger(tela_analisador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_abrir_arquivoActionPerformed

    private void btn_limpar_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_entradaActionPerformed
        // TODO add your handling code here:
        txt_entrada.setText(null);
    }//GEN-LAST:event_btn_limpar_entradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_analisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tela_analisador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea analise_lexica_txt;
    private javax.swing.JTextArea analise_sintatica_txt;
    private javax.swing.JButton btn_abrir_arquivo;
    private javax.swing.JButton btn_analise_lexica;
    private javax.swing.JButton btn_analise_sintatica;
    private javax.swing.JButton btn_limpar_entrada;
    private javax.swing.JButton btn_limpar_lexico;
    private javax.swing.JButton btn_limpar_sintatico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel painel_lexico;
    private javax.swing.JPanel painel_sintatico;
    private javax.swing.JTextArea txt_entrada;
    // End of variables declaration//GEN-END:variables
}
